// Example frontend configuration file
// This file is for documentation purposes only
//
// The actual config.js file is auto-generated by scripts/generate_frontend_config.sh
// when you run ./start_frontend.sh
//
// To customize the backend API URL, set the BACKEND_API_URL environment variable:
//
// Local development (default):
//   ./start_frontend.sh
//   (uses http://localhost:8000)
//
// Production deployment:
//   export BACKEND_API_URL="https://vitos-api.lianglab.net"
//   ./start_frontend.sh
//
// Or inline:
//   BACKEND_API_URL="https://vitos-api.lianglab.net" ./start_frontend.sh

window.VITOS_CONFIG = {
    // Backend API base URL (without /api/v1 suffix)
    BACKEND_API_URL: 'http://localhost:8000'
};
