#!/bin/bash
#
# Generate frontend configuration from environment variables
# This script is automatically called by start_frontend.sh
#

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
FRONTEND_DIR="$PROJECT_DIR/frontend"

# Default backend API URL if not set in environment
DEFAULT_BACKEND_API_URL="http://localhost:8000"

# Use environment variable or default
BACKEND_API_URL="${BACKEND_API_URL:-$DEFAULT_BACKEND_API_URL}"

# Generate config.js file
CONFIG_FILE="$FRONTEND_DIR/config.js"

cat > "$CONFIG_FILE" << EOF
// Auto-generated configuration file
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate_frontend_config.sh
// Generated at: $(date)

window.VITOS_CONFIG = {
    BACKEND_API_URL: '${BACKEND_API_URL}'
};
EOF

echo "✓ Generated frontend config: $CONFIG_FILE"
echo "  BACKEND_API_URL: $BACKEND_API_URL"
